Cambio de workflow para diferenciar entre análisis

diff --git a/.github/workflows/sonarqube-analysis.yml b/.github/workflows/sonarqube-analysis.yml
--- a/.github/workflows/sonarqube-analysis.yml
+++ b/.github/workflows/sonarqube-analysis.yml
@@ -60,7 +60,7 @@ jobs:
       - name: Análisis en pull request
         if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.base_ref == 'develop')
         uses: sonarsource/sonarqube-scan-action@v4
-        id: sonarqube
+        id: sonarqube_pr
         with:
           args: >
             -Dsonar.projectVersion=${{ inputs.version }}
@@ -87,8 +87,17 @@ jobs:
           path: sonar-report.json
 
       - name: Evaluate SonarQube Result
+        if: github.event_name == 'workflow_dispatch' || contains(inputs.entorno, 'production')
         run: |
           if [ "${{ steps.sonarqube.outcome }}" != "success" ] && [ "${{ inputs.entorno }}" == "production" ]; then
             echo "SonarQube step failed with outcome: ${{ steps.sonarqube.outcome }}"
+            exit 1
+          fi
+
+      - name: Evaluate SonarQube Result
+        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.base_ref == 'develop')
+        run: |
+          if [ "${{ steps.sonarqube_pr.outcome }}" != "success" ] && [ "${{ inputs.entorno }}" == "production" ]; then
+            echo "SonarQube step failed with outcome: ${{ steps.sonarqube_pr.outcome }}"
             exit 1
           fi
